# Generated by Django 3.2.8 on 2021-12-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0002_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias_semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=40)),
                ('lunes', models.CharField(max_length=40)),
                ('martes', models.CharField(max_length=40)),
                ('miercoles', models.CharField(max_length=40)),
                ('jueves', models.CharField(max_length=40)),
                ('viernes', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='horas_semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=40)),
                ('lunes_hora', models.CharField(max_length=40)),
                ('martes_hora', models.CharField(max_length=40)),
                ('miercoles_hora', models.CharField(max_length=40)),
                ('jueves_hora', models.CharField(max_length=40)),
                ('viernes_hora', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
