# Generated by Django 3.2.8 on 2021-12-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionDatos', '0003_auto_20211201_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('asignatura', models.CharField(max_length=30)),
                ('tipo_evaluacion', models.CharField(max_length=30)),
                ('promedio', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='identificacion',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
